/**
 * Sub-Agent Execution (Paperclip-style hierarchical orchestration)
 *
 * When a parent agent (e.g., Manufacturing) runs complex work, it can spawn sub-agents
 * (Supply Chain, QA) that run in parallel. Each sub-agent has:
 * - Scope (areas of responsibility)
 * - Spend cap (allocated from parent's budget)
 * - Blocking dependencies (waits for other sub-agents)
 *
 * Policy enforces:
 * - Sub-agent spend ≤ allocated cap
 * - Parent's total sub-spend ≤ parent's spend cap
 * - If parent proposes work, amount must fit allocation
 */

import type { SubAgent, SubAgentStatus, Activity, AgentRole } from "./types";

/* ── Sub-Agent Spawning ────────────────────────────────────────── */

export interface SubAgentTemplate {
  name: string;
  focus: string;
  scopeAreas: string[];
  portionOfParentCap: number; // 0.0-1.0, must sum to ≤1.0
}

/**
 * Spawn sub-agents from a template when a parent agent is assigned complex work.
 *
 * Example:
 *   Manufacturing agent is assigned "reduce cost per unit by 15%"
 *   → spawnSubAgents({ parentId: "manufacturing", parentSpendCap: 200000 }, MANUFACTURING_TEMPLATES)
 *   → Returns: [
 *       { name: "Supply Chain Agent", spendCap: 120000 },
 *       { name: "Quality Agent", spendCap: 80000 }
 *     ]
 */
export function spawnSubAgents(
  parentId: string,
  parentAgentRole: AgentRole,
  parentSpendCap: number,
  templates: SubAgentTemplate[],
  makeId: () => string = () => crypto.randomUUID()
): SubAgent[] {
  const subAgents: SubAgent[] = [];
  let totalAllocated = 0;

  for (const template of templates) {
    const allocated = Math.round(parentSpendCap * template.portionOfParentCap);

    // Sanity check: don't over-allocate
    if (totalAllocated + allocated > parentSpendCap) {
      console.warn(
        `Sub-agent allocation for ${template.name} would exceed parent cap; capping`
      );
      continue;
    }

    const subAgent: SubAgent = {
      id: makeId(),
      name: template.name,
      parentAgentId: parentId,
      scope: template.scopeAreas,
      blockingOn: [],
      status: "idle",
      spendCap: allocated,
      allocated,
      spent: 0,
    };

    subAgents.push(subAgent);
    totalAllocated += allocated;
  }

  return subAgents;
}

/* ── Execution & Spend Tracking ────────────────────────────────── */

/**
 * Record spending by a sub-agent.
 * Returns true if within cap; false if would exceed.
 */
export function recordSubAgentSpend(subAgent: SubAgent, amount: number): boolean {
  if (subAgent.spent + amount > subAgent.allocated) {
    return false; // Over cap
  }
  subAgent.spent += amount;
  return true;
}

/**
 * Check if a sub-agent can spend a given amount without exceeding its cap.
 */
export function canSpend(subAgent: SubAgent, amount: number): boolean {
  return subAgent.spent + amount <= subAgent.allocated;
}

/**
 * Get remaining budget for a sub-agent.
 */
export function remainingBudget(subAgent: SubAgent): number {
  return subAgent.allocated - subAgent.spent;
}

/* ── Parallel Execution & Blocking ────────────────────────────────– */

/**
 * Execute sub-agents in parallel, respecting blocking dependencies.
 *
 * Example:
 *   subAgents = [
 *     { name: "Supply Chain", blockingOn: [] },          // runs immediately
 *     { name: "Quality", blockingOn: ["Supply Chain"] }  // waits for Supply Chain
 *   ]
 *
 * Returns: activities generated by each sub-agent in order
 */
export async function executeSubAgentsSequential(
  subAgents: SubAgent[],
  parentActivity: Activity,
  onExecute: (subAgent: SubAgent) => Promise<Activity>
): Promise<Activity[]> {
  const results: Activity[] = [];
  const completed = new Set<string>();

  // Build a map for easier lookup
  const agentsById = new Map(subAgents.map((sa) => [sa.id, sa]));

  // Topological sort to respect blocking dependencies
  const sorted = topologicalSort(subAgents, agentsById);

  for (const subAgent of sorted) {
    // Check if all blockers are done
    const canRun = subAgent.blockingOn.every((blockerId) => completed.has(blockerId));

    if (!canRun) {
      console.warn(
        `Sub-agent ${subAgent.name} blocked on incomplete dependencies; skipping`
      );
      subAgent.status = "blocked";
      continue;
    }

    try {
      subAgent.status = "running";
      const activity = await onExecute(subAgent);
      activity.parentActivityId = parentActivity.id;
      results.push(activity);

      completed.add(subAgent.id);
      subAgent.status = "done";
    } catch (err) {
      console.error(`Sub-agent ${subAgent.name} failed:`, err);
      subAgent.status = "failed";
    }
  }

  return results;
}

/* ── Topological Sort (for respecting blocking dependencies) ────── */

function topologicalSort(
  subAgents: SubAgent[],
  agentsById: Map<string, SubAgent>
): SubAgent[] {
  const sorted: SubAgent[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  function visit(id: string) {
    if (visited.has(id)) return;
    if (visiting.has(id)) {
      console.warn(`Circular dependency detected for agent ${id}`);
      return;
    }

    visiting.add(id);
    const agent = agentsById.get(id);

    if (agent) {
      for (const blockerId of agent.blockingOn) {
        visit(blockerId);
      }
    }

    visiting.delete(id);
    visited.add(id);

    if (agent) {
      sorted.push(agent);
    }
  }

  for (const agent of subAgents) {
    visit(agent.id);
  }

  return sorted;
}

/* ── Sub-Agent Status Aggregation ────────────────────────────────– */

export function aggregateSubAgentStatus(subAgents: SubAgent[]): SubAgentStatus {
  if (subAgents.length === 0) return "idle";

  const statuses = subAgents.map((s) => s.status);

  if (statuses.some((s) => s === "running")) return "running";
  if (statuses.some((s) => s === "blocked")) return "blocked";
  if (statuses.some((s) => s === "waiting_approval")) return "waiting_approval";
  if (statuses.every((s) => s === "done")) return "done";
  if (statuses.some((s) => s === "failed")) return "failed";

  return "idle";
}

/* ── Known Sub-Agent Templates (for major agent roles) ────────────– */

export const MANUFACTURING_SUB_AGENTS: SubAgentTemplate[] = [
  {
    name: "Supply Chain Agent",
    focus: "Sourcing, supplier relationships, logistics, demand forecasting",
    scopeAreas: ["supplier_management", "sourcing", "logistics", "forecasting"],
    portionOfParentCap: 0.6,
  },
  {
    name: "Quality Agent",
    focus: "Testing, quality assurance, defect analysis, recalls",
    scopeAreas: ["quality_assurance", "testing", "defect_analysis", "recalls"],
    portionOfParentCap: 0.4,
  },
];

const ENGINEERING_SUB_AGENTS: SubAgentTemplate[] = [
  {
    name: "Firmware Engineer",
    focus: "Embedded systems, motor control, BMS, thermal management",
    scopeAreas: ["firmware", "embedded", "motor_control", "safety_critical"],
    portionOfParentCap: 0.5,
  },
  {
    name: "ML/AI Engineer",
    focus: "Autonomous systems, neural networks, model training",
    scopeAreas: ["ml", "ai", "neural_networks", "inference"],
    portionOfParentCap: 0.35,
  },
  {
    name: "Infrastructure Engineer",
    focus: "Cloud architecture, CI/CD, DevOps, monitoring",
    scopeAreas: ["cloud", "devops", "ci_cd", "monitoring"],
    portionOfParentCap: 0.15,
  },
];

const GROWTH_SUB_AGENTS: SubAgentTemplate[] = [
  {
    name: "Demand Generation Agent",
    focus: "Paid ads, conversion optimization, funnel analysis",
    scopeAreas: ["paid_ads", "conversion", "analytics", "funnel"],
    portionOfParentCap: 0.5,
  },
  {
    name: "Content Agent",
    focus: "Blog, social media, PR, brand narrative",
    scopeAreas: ["content", "social", "pr", "brand"],
    portionOfParentCap: 0.5,
  },
];

export function getSubAgentTemplates(parentRole: AgentRole): SubAgentTemplate[] {
  switch (parentRole) {
    case "manufacturing":
      return MANUFACTURING_SUB_AGENTS;
    case "engineering":
      return ENGINEERING_SUB_AGENTS;
    case "growth":
      return GROWTH_SUB_AGENTS;
    default:
      return [];
  }
}
